### ISSUE TITLE
Error when Scaffolding model

### ISSUE THREAD

**Issue by nbsoftware** [AltairCA/EntityFrameworkCore.PostgreSQL.ColumnEncryption#5]
I'm trying to compile the EF model using:

```dotnet ef dbcontext optimize --context XXXDbContext -o XXXDbContext -n XXXDbContext```

and I'm getting an error precisely on a property that has a `[NpgsqlEncrypt]` attribute:

```
Build started...
Build succeeded.
System.InvalidOperationException: The property 'TrustChainAudit.ObjectData' has a value converter configured using a ValueConverter instance or inline expressions. Instead, create a type that inherits from ValueConverter and use 'HasConversion=<ConverterType=>()' or 'HasConversion(Type converterType)' to configure the value converter.
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator.Create(IProperty property, Dictionary`2 propertyVariables, CSharpRuntimeAnnotationCodeGeneratorParameters parameters)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator.CreateEntityType(IEntityType entityType, IndentedStringBuilder mainBuilder, IndentedStringBuilder methodBuilder, SortedSet`1 namespaces, String className, Boolean nullable)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator.GenerateEntityType(IEntityType entityType, String namespace, String className, Boolean nullable)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator.GenerateModel(IModel model, CompiledModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CompiledModelScaffolder.ScaffoldModel(IModel model, String outputDir, CompiledModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.Optimize(String outputDir, String modelNamespace, String contextTypeName)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OptimizeContextImpl(String outputDir, String modelNamespace, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OptimizeContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The property 'TrustChainAudit.ObjectData' has a value converter configured using a ValueConverter instance or inline expressions. Instead, create a type that inherits from ValueConverter and use 'HasConversion=<ConverterType=>()' or 'HasConversion(Type converterType)' to configure the value converter.
```

**Comment by nbsoftware** [comment]
Maybe not easy to fix because of:
- https://github.com/dotnet/efcore/issues/13947
- https://github.com/dotnet/efcore/issues/12205
